import argparse
from io import StringIO

from skbio import TreeNode


def get_argument_parser():
    parser = argparse.ArgumentParser(
        description="Fix the tree files generated by MAFFT.\n\nTree files "
                    "generated by MAFFT do not contain a closing semi-colon, "
                    "and therefore scikit-bio is unable to read them. They "
                    "also modify the name of the sequences, so we revert that "
                    "change to be able to compare the trees using "
                    "Robinson-Foulds."
    )

    parser.add_argument('infile', help="The tree file to fix")
    parser.add_argument('outfile', help="The output file. If not specified "
                                        "file will be modified inplace.",
                        default="", nargs="?")

    return parser

if __name__ == '__main__':
    parser = get_argument_parser()
    args = parser.parse_args()

    newick = ""
    with open(args.infile) as f:
        newick = f.read()
        newick += ";"

    fh = StringIO(newick)
    tree = TreeNode.read(fh, format='newick')

    for node in tree.preorder():
        if node.name:
            node.name = "_".join(node.name.split(' ')[1:])

    outfile = args.outfile or args.infile

    with open(outfile, 'w') as fh:
        tree.write(fh, format='newick')
